from csgo_analysis.ingestion.models.db import Lookup


class ItemType:

    _EQUIPMENT = Lookup(0, 'equipment')
    _PISTOL = Lookup(1, 'pistol')
    _SMG = Lookup(2, 'smg')
    _SHOTGUN = Lookup(3, 'shotgun')
    _LMG = Lookup(4, 'lmg')
    _RIFLE = Lookup(5, 'rifle')
    _SNIPER = Lookup(6, 'sniper')
    _GRENADE = Lookup(7, 'grenade')
    _MELEE = Lookup(8, 'melee')


class Items:

    _CZ75A = Lookup(1, 'weapon_cz75a')
    _DEAGLE = Lookup(2, 'weapon_deagle')
    _ELITE = Lookup(3, 'weapon_elite')
    _FIVESEVEN = Lookup(4, 'weapon_fiveseven')
    _GLOCK = Lookup(5, 'weapon_glock')
    _HKP2000 = Lookup(6, 'weapon_hkp2000')
    _P250 = Lookup(7, 'weapon_p250')
    _REVOLVER = Lookup(8, 'weapon_revolver')
    _TEC9 = Lookup(9, 'weapon_tec9')
    _USP_SILENCER = Lookup(10, 'weapon_usp_silencer')
    _MAG7 = Lookup(11, 'weapon_mag7')
    _NOVA = Lookup(12, 'weapon_nova')
    _SAWEDOFF = Lookup(13, 'weapon_sawedoff')
    _XM1014 = Lookup(14, 'weapon_xm1014')
    _M249 = Lookup(15, 'weapon_m249')
    _NEGEV = Lookup(16, 'weapon_negev')
    _MAC10 = Lookup(17, 'weapon_mac10')
    _MP5SD = Lookup(18, 'weapon_mp5sd')
    _MP7 = Lookup(19, 'weapon_mp7')
    _MP9 = Lookup(20, 'weapon_mp9')
    _P90 = Lookup(21, 'weapon_p90')
    _BIZON = Lookup(22, 'weapon_bizon')
    _UMP45 = Lookup(23, 'weapon_ump45')
    _AK47 = Lookup(24, 'weapon_ak47')
    _AUG = Lookup(25, 'weapon_aug')
    _FAMAS = Lookup(26, 'weapon_famas')
    _GALILAR = Lookup(27, 'weapon_galilar')
    _M4A1_SILENCER = Lookup(28, 'weapon_m4a1_silencer')
    _M4A1 = Lookup(29, 'weapon_m4a1')
    _SG556 = Lookup(30, 'weapon_sg556')
    _AWP = Lookup(31, 'weapon_awp')
    _G3SG1 = Lookup(32, 'weapon_g3sg1')
    _SCAR20 = Lookup(33, 'weapon_scar20')
    _SSG08 = Lookup(34, 'weapon_ssg08')
    _TASER = Lookup(35, 'weapon_taser')
    _HEGRENADE = Lookup(36, 'weapon_hegrenade')
    _FLASHBANG = Lookup(37, 'weapon_flashbang')
    _SMOKEGRENADE = Lookup(38, 'weapon_smokegrenade')
    _INCGRENADE = Lookup(39, 'weapon_incgrenade')
    _MOLOTOV = Lookup(40, 'weapon_molotov')
    _DECOY = Lookup(41, 'weapon_decoy')
    _KNIFE = Lookup(42, 'weapon_knife')
    _KNIFE_T = Lookup(42, 'weapon_knife_t')
    _KNIFEGG = Lookup(42, 'weapon_knifegg')
    _KNIFE_CSS = Lookup(42, 'weapon_knife_css')
    _BAYONET = Lookup(42, 'weapon_bayonet')
    _KNIFE_FLIP = Lookup(42, 'weapon_knife_flip')
    _KNIFE_GUT = Lookup(42, 'weapon_knife_gut')
    _KNIFE_KARAMBIT = Lookup(42, 'weapon_knife_karambit')
    _KNIFE_M9_BAYONET = Lookup(42, 'weapon_knife_m9_bayonet')
    _KNIFE_TACTICAL = Lookup(42, 'weapon_knife_tactical')
    _KNIFE_BUTTERFLY = Lookup(42, 'weapon_knife_butterfly')
    _KNIFE_FALCHION = Lookup(42, 'weapon_knife_falchion')
    _KNIFE_PUSH = (42, 'weapon_knife_push')
    _KNIFE_SURVIVAL = Lookup(42, 'weapon_knife_survival')
    _KNIFE_URSUS = Lookup(42, 'weapon_knife_ursus')
    _KNIFE_GYPSY_JACKKNIFE = Lookup(42, 'weapon_knife_gypsy_jackknife')
    _KNIFE_STILETTO = Lookup(42, 'weapon_knife_stiletto')
    _KNIFE_WIDOWMAKER = Lookup(42, 'weapon_knife_widowmaker')
    _KNIFE_GHOST = Lookup(42, 'weapon_knife_ghost')
    _KNIFE_CANIS = Lookup(42, 'weapon_knife_canis')
    _KNIFE_CORD = Lookup(42, 'weapon_knife_cord')
    _KNIFE_SKELETON = Lookup(42, 'weapon_knife_skeleton')
    _KNIFE_OUTDOOR = Lookup(42, 'weapon_knife_outdoor')
    _KEVLAR = Lookup(65, 'item_kevlar')
    _ASSAULTSUIT = Lookup(66, 'item_assaultsuit')
    _DEFUSER = Lookup(67, 'item_defuser')
    _C4 = Lookup(68, 'c4')

    @ staticmethod
    def short_wep(item):
        return item.__name__
